baseURL = "https://chrisrichards.co.uk/"
languageCode = "en-gb"
title = "Chris Richards"
theme = "paper"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  color = 'linen'
  favicon = ""
  description = "Chris Richards"
  facebook = ""
  twitter = "https://twitter.com/crichards2000"
  instagram = ""
  youtube = ""
  github = "https://github.com/chrisrichards"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/chris-richards-52a5481/"
  mastodon = "@chrisrichards@mastodon.social"
  slack = ""
  stackoverflow = "https://stackoverflow.com/users/251441/chrisr"

  avatar = 'chris@chrisrichards.co.uk'
  name = 'Chris'

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    identifier = "now"
    name = "Now"
    url = "/now/"
    weight = 20
